version: '3'

services:
  aws-cli:
    container_name: aws-cli
    build:
      context: .
      dockerfile: awscli.Dockerfile
    tty: true
    # Docker outside of Docker
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    # 環境変数
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
